version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: barber-postgres
    environment:
      POSTGRES_DB: barber_saas
      POSTGRES_USER: barber_user
      POSTGRES_PASSWORD: barber_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barber_user -d barber_saas"]
      interval: 10s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3.8
    container_name: barber-localstack
    environment:
      SERVICES: sqs,sns,dynamodb
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
      PERSISTENCE: 1
    ports:
      - "4566:4566"
    volumes:
      - ./infra/docker/localstack/state:/var/lib/localstack
      - ./infra/docker/localstack/init:/etc/localstack/init
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: