spring:
  application:
    name: booking-service

server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} correlationId=%X{correlationId} - %msg%n"