spring:
  application:
    name: availability-service
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566

server:
  port: 8082

barbersaas:
  messaging:
    booking-events-topic: booking-events
    booking-created-queue: booking-created-queue
    availability-events-topic: availability-events
    availability-decided-queue: availability-decided-queue
    booking-events-dlq: booking-events-dlq
    availability-events-dlq: availability-events-dlq
    booking-created-kafka-topic: booking-created-kafka
    availability-kafka-consumer-group: availability-booking-created-group
    kafka-bootstrap-servers: localhost:9092
    kafka-listener-auto-startup: true