apiVersion: apps/v1
kind: Deployment

metadata:
  name: availability-service

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: availability-service

  template:
    metadata:
      labels:
        app: availability-service

    spec:
      containers:
        - name: availability-service
          image: barber-availability-service:8.4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          env:
            - name: SERVER_PORT
              value: "8082"

            - name: DB_URL
              value: "jdbc:postgresql://host.docker.internal:5432/barbersaas?currentSchema=availability"

          envFrom:
            - configMapRef:
                name: barber-saas-config

            - secretRef:
                name: barber-saas-secret

          livenessProbe:
            httpGet:
              path: /livez
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3