apiVersion: batch/v1
kind: Job

metadata:
  name: kafka-init

spec:
  backoffLimit: 10

  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: kafka-init
          image: apache/kafka:4.1.2

          command:
            - /bin/sh
            - -c
            - |
              until /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --list >/dev/null 2>&1; do
                echo "Waiting for Kafka..."
                sleep 5
              done

              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --create \
                --if-not-exists \
                --topic booking-created-kafka \
                --partitions 3 \
                --replication-factor 1

              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --list