apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: barbersaas

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: barber-saas-db-secret
                  key: DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barber-saas-db-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - barbersaas
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: postgres-data
          emptyDir: {}

---

apiVersion: v1
kind: Service

metadata:
  name: postgres

spec:
  type: ClusterIP

  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432