apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: booking-service

  template:
    metadata:
      labels:
        app: booking-service

    spec:
      containers:
        - name: booking-service
          image: barber-booking-service:8.4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: SERVER_PORT
              value: "8081"

            - name: DB_URL
              value: "jdbc:postgresql://host.docker.internal:5432/barbersaas?currentSchema=booking"

          envFrom:
            - configMapRef:
                name: barber-saas-config

            - secretRef:
                name: barber-saas-secret

          livenessProbe:
            httpGet:
              path: /livez
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3